name: Generate metrics

on:
  workflow_dispatch:
  schedule: 
    - cron: "20 4 * * */2"

jobs:
  gen-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.PAT }}
