name: Generate metrics

on:
  workflow_dispatch:
  schedule: 
    - cron: "20 4 * * */2"

jobs:
  gen-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: actions/create-github-app-token@v1
        id: create-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ steps.create-token.outputs.token }}
